import {
   AlignCenter,
   AlignJustify,
   AlignLeft,
   AlignRight,
   Ban,
   Bold,
   Captions,
   CaseSensitive,
   Check,
   ChevronDown,
   Clipboard,
   Code,
   Combine,
   Download,
   Edit,
   Eraser,
   ExternalLink,
   FileCode,
   FileText,
   Image,
   IndentDecrease,
   IndentIncrease,
   Italic,
   Link,
   List,
   ListOrdered,
   ListTodo,
   Maximize,
   Minimize,
   Minus,
   MoveHorizontal,
   Palette,
   Plus,
   Redo,
   Ruler,
   SeparatorHorizontal,
   Strikethrough,
   Subscript,
   Superscript,
   Table,
   TableColumnsSplit,
   TableProperties,
   TableRowsSplit,
   Trash,
   Underline,
   Undo,
   Unlink,
   X,
   Youtube,
   type LucideIcon,
} from 'lucide-react';
import IconCorner from './Corner';
import IconInlineCode from './InlineCode';
import IconQuote from './Quote';
import IconTextColor from './TextColor';
import IconTextHighlight from './TextHighlight';

export const icons = {
   Bold: Bold,
   Italic: Italic,
   Underline: Underline,
   Strike: Strikethrough,
   Code: Code,
   SourceCode: FileCode,
   Subscript: Subscript,
   Superscript: Superscript,
   BulletList: List,
   OrderedList: ListOrdered,
   TaskList: ListTodo,
   CodeBlock: Code,
   CodeInline: IconInlineCode,
   Link: Link,
   Unlink: Unlink,
   Edit: Edit,
   ExternalLink: ExternalLink,
   Redo: Redo,
   Undo: Undo,
   AlignLeft: AlignLeft,
   AlignRight: AlignRight,
   AlignJustify: AlignJustify,
   AlignCenter: AlignCenter,
   Eraser: Eraser,
   ChevronDown: ChevronDown,
   Maximize: Maximize,
   Minimize: Minimize,
   HorizontalRule: Minus,
   Indent: IndentIncrease,
   Outdent: IndentDecrease,
   Clipboard: Clipboard,
   Check: Check,
   Quote: IconQuote,
   Corner: IconCorner,
   LetterCase: CaseSensitive,
   Trash: Trash,
   Image: Image,
   ImageCaption: Captions,
   ImageAltText: FileText,
   Download: Download,
   Youtube: Youtube,
   Close: X,
   Ruler: Ruler,
   TextHighlight: IconTextHighlight,
   TextColor: IconTextColor,
   Palette: Palette,
   PaletteOff: Palette,
   Ban: Ban,
   Plus: Plus,
   Table: Table,
   Stretch: MoveHorizontal,
   HeaderRow: TableRowsSplit,
   HeaderCol: TableColumnsSplit,
   ColInsertLeft: TableProperties,
   ColInsertRight: TableProperties,
   ColRemove: TableProperties,
   ColHeader: TableColumnsSplit,
   RowInsertTop: TableProperties,
   RowInsertBottom: TableProperties,
   RowRemove: TableProperties,
   RowHeader: TableRowsSplit,
   MergeCell: Combine,
   SplitCell: SeparatorHorizontal,
} satisfies Record<string, LucideIcon>;

export type { LucideIcon };
